# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 04:49
from __future__ import unicode_literals

from django.db import migrations
import utils.fields.custom_imagefield


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20170801_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_cover',
            field=utils.fields.custom_imagefield.CustomImageField(blank=True, upload_to='post'),
        ),
    ]
